const SITE_ARTICLES = [
  { title: "5 Simple Morning Habits for a Calmer Day", url: "article.html", category: "mind" },
  { title: "How to Actually Wind Down at Night", url: "wind-down.html", category: "sleep" },
  { title: "Simple Stretches for People Who Sit All Day", url: "stretches.html", category: "body" },
  { title: "How to Reduce Screen Time Without Feeling Deprived", url: "screen-time.html", category: "mind" },
  { title: "A 2-Minute Breathing Exercise for Anxious Moments", url: "breathing.html", category: "body" },
  { title: "Understanding Your Heart: A Simple Guide to Heart Health", url: "heart-health.html", category: "body" },
  { title: "How Your Brain Works: A Simple Guide", url: "brain-health.html", category: "mind" },
  { title: "Why Dehydration Affects You More Than You Realize", url: "dehydration.html", category: "body" },
  { title: "Simple Habits to Protect Your Eyesight", url: "eye-health.html", category: "body" },
  { title: "Understanding Your Kidneys", url: "kidney-health.html", category: "body" },
  { title: "What Your Skin Is Trying to Tell You", url: "skin-health.html", category: "body" },
  { title: "Why Your Hair Gets Weak — And How to Support It", url: "hair-health.html", category: "body" },
  { title: "Caring for Your Teeth and Nails", url: "teeth-nails-health.html", category: "body" },
  { title: "Mouth Ulcers, Sores, and Oral Germs", url: "oral-health.html", category: "body" },
  { title: "How Blood Circulation Works", url: "blood-circulation.html", category: "body" },
  { title: "Keeping Your Joints and Bones Strong", url: "joint-bone-health.html", category: "body" },
  { title: "How Your Immune System Really Works", url: "immune-system.html", category: "body" },
  { title: "Understanding Your Gut: Digestive Health", url: "gut-health.html", category: "body" },
  { title: "High Blood Pressure: What You Need to Know", url: "blood-pressure.html", category: "body" },
  { title: "Cholesterol Explained: Good, Bad, and What to Do", url: "cholesterol.html", category: "body" },
  { title: "Blood Sugar and Diabetes: A Simple Guide", url: "blood-sugar.html", category: "body" },
  { title: "How Metabolism Actually Works", url: "weight-loss-metabolism.html", category: "body" },
  { title: "Understanding Anxiety", url: "anxiety-explained.html", category: "mind" },
  { title: "Your Thyroid: The Small Gland With a Big Job", url: "thyroid-health.html", category: "body" },
  { title: "Why Your Back Hurts (And What Actually Helps)", url: "back-pain.html", category: "body" },
  { title: "Understanding Cancer: How It Develops", url: "understanding-cancer.html", category: "body" },
  { title: "Foodborne and Waterborne Illness", url: "foodborne-waterborne-illness.html", category: "body" },
  { title: "Colds vs. Flu: The Actual Difference", url: "cold-and-flu.html", category: "body" },
  { title: "Vitamins and Minerals: What Your Body Needs", url: "vitamins-minerals.html", category: "body" },
  { title: "Ear Health and Hearing: A Simple Guide", url: "ear-health-hearing.html", category: "body" },
  { title: "Understanding Allergies", url: "understanding-allergies.html", category: "body" },
  { title: "Why Posture Matters More Than You Think", url: "posture-and-health.html", category: "body" },
  { title: "Apples: A Complete Health Guide", url: "apples-health-guide.html", category: "body" }
];
